# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/n8n_cerimibau',
                'doc_host': 'https://6ent.github.io',
                'git_url': 'https://github.com/6ent/n8n_cerimibau',
                'lib_path': 'n8n_cerimibau'},
  'syms': { 'n8n_cerimibau.core': {'n8n_cerimibau.core.foo': ('core.html#foo', 'n8n_cerimibau/core.py')},
            'n8n_cerimibau.plotter.fenster_plotter_utils': { 'n8n_cerimibau.plotter.fenster_plotter_utils.draw_mechanism': ( 'plotter/fenster_plotter_utils.html#draw_mechanism',
                                                                                                                             'n8n_cerimibau/plotter/fenster_plotter_utils.py'),
                                                             'n8n_cerimibau.plotter.fenster_plotter_utils.draw_window_with_dimensions': ( 'plotter/fenster_plotter_utils.html#draw_window_with_dimensions',
                                                                                                                                          'n8n_cerimibau/plotter/fenster_plotter_utils.py')}}}
